### ISSUE TITLE
Ajustements pré-publication

### ISSUE THREAD

**Issue by n-b** [velo-iledefrance/observatoire-vif#41]
- [x] Affichage des statistiques par département dans la console (#38)
- [x] hachures pour toutes les variantes (#39)
    - nouvelles couleurs
- [x] rendre les tracés “à l’étude” moins visibles (trait fin) (#39)
- [x] compléter les légendes pour toutes les couleurs (#40)
    - [x] améliorer le wording de la légende des variantes  (#40)
- [x] bugs sur les segments — probablement un tronçon qui a été remplacé par plusieurs
    il y a trois cas:
    - [x] les données réimportées disparues
        ``` 
        select id, values->>'ecd6370d-9528-472c-aff6-89759a95742d' as voie, values->>'b82c12d1-95c7-4da9-82ad-2c13f38fadd3' as global_id from rows where values->>'b82c12d1-95c7-4da9-82ad-2c13f38fadd3' not in
        ('{3FF7AE71-DEB0-4C33-91ED-C1D545C50AC3}',
        …
        )
        ```
        ```
                                  id                  |       voie       |               global_id                
        --------------------------------------+------------------+----------------------------------------
         4a1bc17c-6dc9-4de5-8794-45de4d8a00a7 | V6EV20-260-94028 | {D6923FA5-E971-4FF8-A842-799E7B02D4F0}
         ce938d3e-a486-422e-8322-794b64861360 | V4E-130m2-93030  | {8EE867F5-45A1-4EA2-A2EA-751BD20C73B7}
         943fad3d-20e3-414d-8834-284f35b83436 | V4E-132m2-93030  | {AC13FB37-575C-4A67-B5D0-43BFD5D19050}
         67e6d433-6f59-458f-bcf8-b4ea261be5e4 | V5EV6E-090-94018 | {4533CF02-4609-4FE3-A07A-31924AAD0A5F}
         6c7a0ae6-6b07-4cab-b08a-8da8b5673553 | V6EV20-260-94028 | {19364C2E-8F6F-49A1-976E-8DC9D51BEA3B}
        (5 rows)
        ```
    - [x] les rows vides
         - place de la nation et la place de la concorde existent bien en doublons, mais surtout (et pompadour aussi) n’ont pas de NUM_LIGNE.
         - il y avait une dizaine de rows vides qui étaient des doublons de rows valides et que nous avons supprimés.
    - [x] dans l’observatoire, on `group by code_tronçon`, ce qui en principe n’a pas de sens (on sait que le code tronçon n’est pas unique) (ce dernier point est-il lié à la façon dont on gère les multipolyline?)
- [x] afficher le commentaire y compris si le tronçon n‘est pas bloqué
- [x] étudier si la colonne « à terme » peut aider à affiner les calculs de longueur
    > Bonjour Rivo
    > Nous avons commencé à corriger les données mais avec les vacances, il en reste encore à vérifier.
    Normalement tout devrait être corrigé dans la journée de lundi.
    > Je te propose de prendre l’attache de Romain et Pascal mardi pour vérifier les calculs des linéaires comme nous l’avions ensemble vu la semaine dernière.
    > Enfin, l’explication du « Définitif long terme » que nous avons mis. Il nous permet de connaitre la section qui sera concernée par l’itinéraire à terme et les sections concernées par un itinéraire provisoire. Pour les linéaires des lignes du coup, on prend soit les « définitifs à terme » soit les « Provisoires ».
    > Ainsi, nous avons fait le choix la communication sur les linéaires de :
    > -  Prendre uniquement les itinéraires définitifs, les Provisoires et les NR (donc on exclut les « définitifs à terme »).
    > -  Exclure les variantes
- [x] Mettre en place un réimport automatique (#10)
- [x] Ajouter un contour aux pastilles colorées de la légende.
    Dans la légende, il est difficile de distinguer le préexistant de l’inconnu. Sur la carte, cela se voit mieux, grâce au liseré vert du préexistant. 
- [x] Afficher les Phase 2 mis en service de la même façon que tous les autres phases 2, à savoir en blanc simple. 
    Pour des raisons de clarté : certains tronçons de phase 2 ont un statut de mise en service.
- [x] Unifier la représentation pointillée
    Aujourd’hui c’est défini en fonction de la largeur du trait, ce qui fait que les traits larges (les verts, préexistant, livré et en travaux) sont plus espacés que les traits fins (bleu et rouge, à l’étude et bloqué). Ça ne sera pas forcément les mêmes longueurs en pixels, mais faire au mieux pour que visuellement, ils semblent identiques.

**Comment by Tristramg** [comment]
Le group by sert à afficher tous les numéros de route lorsqu’on clique sur les détails d’un tronçon, même si dans la base de la région ce sont des tronçons différents, à chacun sa ligne.

**Comment by Tristramg** [comment]
Cas particulier les V8-X- : la région a laissé les données dans le flux, mais en supprimant des attributs et la géométrie. N’ayant pas de géométrie, cocarto l’a ignoré en mettant un warning à l’import.
N’étant pas supprimé, ça n’a pas été détecté par ma moulinette qui cherchait les identifiants supprimés par la région.

**Comment by Tristramg** [comment]
Pour les définitif long terme la PR est #44
De plus la nouvelle valeur a été définie dans cocarto (elle n’existait pas au début du projet)

**Comment by Tristramg** [comment]
Afficher phase 2 en priorité sur livré (contrairement à ce qui avait été décidé dans le mail du 8 septembre) est dans #45
